export const googleWhite = '#ffffff';
export const googleBlue = ' #4285F4ff';
export const colorPrimary = '#2C5BC8';
export const silverWhite = '#F8F9FC';
export const darkGray = '#707070';
export const eerieBlack = '#1F1F1F';
export const oceanGreen = '#54B98A';
export const imperialRed = '#E24848';
export const yellowOrange = '#FFAD3C';
